### ISSUE TITLE
通过WebsocketTest.php访问远程的websocket 返回乱码

### ISSUE THREAD

**Issue by 1099223026** [xhjcehust/AsyncWebSocketClient#1]
我并没有使用WebsocketServer.php文件，直接通过WebsocketTest.php访问远程主机中存在的socket服务，连接正常打开，但传递参数后，客户端就自动断开了，且接受到了乱码，如下图所示：
![image](https://user-images.githubusercontent.com/22950089/53061411-8f2aee80-34f8-11e9-9a21-dc705fd0c70d.png)

WebsocketTest.PHP文件源码，如下图所示：
![image](https://user-images.githubusercontent.com/22950089/53061687-53445900-34f9-11e9-9e82-bbd5d9fc73b1.png)

也排查过问题，在WebsocketClient.php文件中，打印出了通过pack函数打包后的数据，源码如下图所示：
![image](https://user-images.githubusercontent.com/22950089/53061544-eb8e0e00-34f8-11e9-9ad5-e74b09121694.png)
打印结果，如下图所示：
![image](https://user-images.githubusercontent.com/22950089/53061573-01033800-34f9-11e9-8f2c-da8f8bb94e30.png)
红色框内的便是pack打包后的数据，可以看到，已经开始有乱码字符了。

这个问题已经纠缠了我很久，希望得到回复，在此谢谢了

**Comment by 1099223026** [comment]
@xhjcehust

**Comment by 1099223026** [comment]
@xhjcehust 请问，能帮助我么？

**Comment by xhjcehust** [comment]
pack打包后的数据是二进制数据，打印出来乱码是正常的，远程主机中存在的websocket服务示例代码可以贴下？
